CU-8695pfuj4_Calendar-Tab
n-b-solutions/hershul pull request #28
Opened 2024-09-17 11:32 UTC by zippiL

2024-09-17 11:32 UTC, benshabatnoam commented
Task linked: [CU-8695pfuj4 Calendar Tab](https://app.clickup.com/t/8695pfuj4)
Task linked: [CU-8695uuj68 Get minyans by the date](https://app.clickup.com/t/8695uuj68)

2024-09-18 04:51 UTC, SaraCohenNBS requested changes

2024-09-18 04:51 UTC, SaraCohenNBS commented on server/router/minyanListRouter.ts
> +
Remove console.log

2024-09-18 06:09 UTC, zippiL reviewed
> Just now I get the point what you mean when you say 'getting directly from the API', that not look so good, no other way? 
i didn't find
If you find it, I would be really happy 😌

2024-09-18 06:10 UTC, zippiL commented on server/controller/minyanListController.ts
> +  );
i didn't find
If you find it, I would be really happy 😌

2024-09-18 06:39 UTC, zippiL commented on server/controller/minyanListController.ts
> +const isRoshChodesh = async (): Promise<boolean> => {
Where to put it exactly?
We will pass it on.
May you feel comfortable...

2024-09-18 09:56 UTC, SaraCohenNBS commented on server/controller/minyanListController.ts
> +  );
👍

2024-09-18 09:57 UTC, merged